modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="sandbox"
version="${file.jarVersion}"
displayName="sandbox"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="sandbox.png"
credits="Khorbos"
authors="Khorbos"
description='''
A sandbox minecraft tutorial mod for testing some features
'''

[[dependencies.sandbox]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sandbox]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
